" VIM user configurations. NeoVim configurations are in init.lua
let s:path = expand('<sfile>:p:h')

" Basic configurations
let s:plug_path = s:path . "/basic.vim"
if filereadable(expand(s:plug_path))
	:execute "source" . expand(s:plug_path)
endif

" Plugins
let s:plug_path = s:path . "/plugins.vim"
if filereadable(expand(s:plug_path))
	:execute "source" . expand(s:plug_path)
endif

" Mappings
let s:plug_path = s:path . "/mappings.vim"
if filereadable(expand(s:plug_path))
	:execute "source" . expand(s:plug_path)
endif

" Extra configs
let s:extraconf_path = s:path . "/vimrc.extraconf"
if filereadable(expand(s:extraconf_path))
	:execute "source" . expand(s:extraconf_path)
endif

:command! Wq wq
