let s:path = expand('<sfile>:p:h')
set encoding=utf-8	" Required for vimtex and youcompleteme

filetype on
filetype plugin on
filetype indent on

syntax on
set number
set incsearch
set ls=2
set hlsearch

" tab spacing
set tabstop=4
set shiftwidth=4	" for << and >>

set backspace=indent,eol,start "set backspace so that it can delete newlines

" Set delay for escape sequence
set timeoutlen=1000
set ttimeoutlen=5

" Set fold method
:command -nargs=1 Fdm setlocal foldmethod=<args>

set tags=./tags

" Plugins
let s:plug_path = s:path . "/vimrc.plug"
if filereadable(expand(s:plug_path))
	:execute "source" . expand(s:plug_path)
endif

" Extra configs
let s:extraconf_path = s:path . "/vimrc.extraconf"
if filereadable(expand(s:extraconf_path))
	:execute "source" . expand(s:extraconf_path)
endif

:command! Wq wq
